# -*- coding: utf-8 -*-
"""Pytorch_Text_Classification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-u3JznK-BQszKfeeWfWYfxfNHW4U3DY7
"""

import torch
print("GPU Available :", torch.cuda.is_available())
print("GPU Available", torch.cuda.get_device_name(0) if torch.cuda.is_available() else "None")

import torch
import torch.nn as nn
import torch.optim as optim

from datasets import load_dataset
from transformers import AutoTokenizer
dataset = load_dataset("ag_news")

from huggingface_hub import notebook_login
notebook_login()

tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased")
def tokenize_function(examples):
  return tokenizer(examples["text"], padding = "max_length", truncation=True, max_length = 128)
tokenized_datasets = dataset.map(tokenize_function , batched = True)

#formating dataset for Pytorch

tokenized_datasets = tokenized_datasets.remove_columns(["text"])
tokenized_datasets = tokenized_datasets.rename_column("label", "labels")
tokenized_datasets.set_format("torch")

from torch.utils.data import DataLoader
#Create DataLoaders

train_dataloader =DataLoader(tokenized_datasets["train"] , shuffle = True , batch_size = 23)
test_dataloader =DataLoader(tokenized_datasets["test"] ,batch_size = 23)

from IPython.terminal.embed import embed
import torch.nn as nn
class TextClassifier(nn.Module):
  def __init__(self, vocab_size , embed_dim , num_classes):
    super(TextClassifier, self).__init__()
    self.embedding = nn.Embedding(vocab_size , embed_dim)
    self.fc1 = nn.Linear(embed_dim , 128) #first hidden layer
    self.relu = nn.ReLU() # Activation Function
    self.fc2 = nn.Linear(128, num_classes) # Output layer
  def forward(self, input_ids):
    embedded  =self.embedding(input_ids).mean(dim= 1)
    x = self.fc1(embedded)
    x = self.relu(x)
    output = self.fc2(x)
    return output
vocab_size = tokenizer.vocab_size
embed_dim = 128
num_classes =4
model = TextClassifier(vocab_size , embed_dim , num_classes)

criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters() , lr = 5e-4)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.to(device)

num_epochs= 3
for epoch in range(num_epochs):
  model.train()
  total_loss = 0
  for batch in train_dataloader:
    input_ids = batch["input_ids"].to(device)
    labels = batch["labels"].to(device)
    outputs = model(input_ids)
    loss = criterion(outputs , labels)
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
    total_loss += loss.item()
print(f"Epoch {epoch + 1} , Loss :{total_loss/len(train_dataloader)}")

model.eval()
correct  = 0
total = 0
with torch.no_grad():
  for batch in test_dataloader:
    input_ids = batch["input_ids"].to(device)
    labels = batch["labels"].to(device)
    outputs = model(input_ids)
    predictions = torch.argmax(outputs, dim=1)
    correct += (predictions == labels).sum().item()
    total += labels.size(0)
accuracy = correct / total
print(f"Test Accuracy : {accuracy:.4f}")

def classify_text(text):
  model.eval()
  inputs = tokenizer(text , return_tensors = "pt", padding = "max_length" , truncation=True , max_length=128).to(device)
  with torch.no_grad():
    outputs  =model(inputs["input_ids"])
  prediction = torch.argmax(outputs, dim=1).item()
  categories = ["World", "Sports", "Business", "Sci/Tech"]
  return categories[prediction]

text = "French veteran Gael Monfils becomes the oldest player to win an ATP Tour singles title."
print(f"Predicted Category: {classify_text(text)}")